services:
  postgres_auth:
    image: postgres:16-alpine
    container_name: gobank_postgres_auth
    environment:
      POSTGRES_DB: gobank_auth
      POSTGRES_USER: gobank
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gobank -d gobank_auth"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres_wallet:
    image: postgres:16-alpine
    container_name: gobank_postgres_wallet
    environment:
      POSTGRES_DB: gobank_wallet
      POSTGRES_USER: gobank
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - postgres_wallet_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gobank -d gobank_wallet"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: gobank-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass secret
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "secret", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest
    container_name: gobank-mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: gobank-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: gobank_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 5

  auth:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: auth
    container_name: gobank-auth
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      DB_URL: postgres://gobank:secret@postgres_auth:5432/gobank_auth?sslmode=disable
      JWT_SECRET: secret
      REDIS_URL: redis:6379
      REDIS_PASSWORD: secret
    depends_on:
      postgres_auth:
        condition: service_healthy
      redis:
        condition: service_healthy
  
  wallet:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: wallet
    container_name: gobank_wallet
    ports:
      - "8081:8080"
    environment:
      DB_URL_WALLET: postgres://gobank:secret@postgres_wallet:5432/gobank_wallet?sslmode=disable
      KAFKA_BROKERS: kafka:29092
      AUTH_GRPC_ADDR: auth:9090
    depends_on:
      postgres_wallet:
        condition: service_healthy
      kafka:
        condition: service_healthy
      auth:
        condition: service_started

  notification:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: notification
    container_name: gobank_notification
    environment:
      KAFKA_BROKERS: kafka:29092
    depends_on:
      kafka:
        condition: service_healthy
    

volumes:
  postgres_auth_data:
  postgres_wallet_data: