global:
  scrape_interval: 15s
  evaluation_interval: 15s
  
scrape_configs:
  - job_name: 'gobank-auth'
    static_configs:
      - targets: ['auth:8080']
    metrics_path: /metrics

  - job_name: 'gobank-wallet'
    static_configs:
      - targets: ['wallet:8080']
    metrics_path: /metrics
