// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/AriartyyyA/gobank/internal/wallet/domain"
	mock "github.com/stretchr/testify/mock"
)

// WalletRepository is an autogenerated mock type for the WalletRepository type
type WalletRepository struct {
	mock.Mock
}

// CreateTransaction provides a mock function with given fields: ctx, transaction
func (_m *WalletRepository) CreateTransaction(ctx context.Context, transaction domain.Transaction) error {
	ret := _m.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Transaction) error); ok {
		r0 = rf(ctx, transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateWallet provides a mock function with given fields: ctx, wallet
func (_m *WalletRepository) CreateWallet(ctx context.Context, wallet domain.Wallet) error {
	ret := _m.Called(ctx, wallet)

	if len(ret) == 0 {
		panic("no return value specified for CreateWallet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Wallet) error); ok {
		r0 = rf(ctx, wallet)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindWalletByID provides a mock function with given fields: ctx, walletID
func (_m *WalletRepository) FindWalletByID(ctx context.Context, walletID string) (*domain.Wallet, error) {
	ret := _m.Called(ctx, walletID)

	if len(ret) == 0 {
		panic("no return value specified for FindWalletByID")
	}

	var r0 *domain.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Wallet, error)); ok {
		return rf(ctx, walletID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Wallet); ok {
		r0 = rf(ctx, walletID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, walletID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindWalletByUserID provides a mock function with given fields: ctx, userID
func (_m *WalletRepository) FindWalletByUserID(ctx context.Context, userID string) (*domain.Wallet, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindWalletByUserID")
	}

	var r0 *domain.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Wallet, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Wallet); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Wallet)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionsByWalletID provides a mock function with given fields: ctx, walletID, limit, offset
func (_m *WalletRepository) GetTransactionsByWalletID(ctx context.Context, walletID string, limit string, offset string) ([]*domain.Transaction, error) {
	ret := _m.Called(ctx, walletID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionsByWalletID")
	}

	var r0 []*domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) ([]*domain.Transaction, error)); ok {
		return rf(ctx, walletID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) []*domain.Transaction); ok {
		r0 = rf(ctx, walletID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, walletID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBalance provides a mock function with given fields: ctx, walletID, amount
func (_m *WalletRepository) UpdateBalance(ctx context.Context, walletID string, amount int64) error {
	ret := _m.Called(ctx, walletID, amount)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = rf(ctx, walletID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithTx provides a mock function with given fields: ctx, fn
func (_m *WalletRepository) WithTx(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWalletRepository creates a new instance of WalletRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWalletRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WalletRepository {
	mock := &WalletRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
