apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: gobank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: gobank/auth:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
            - name: grpc
              containerPort: 9090
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: gobank-app-config
                  key: DB_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: gobank-app-secret
                  key: JWT_SECRET
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: gobank-app-config
                  key: REDIS_URL
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gobank-app-secret
                  key: REDIS_PASSWORD
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: gobank-app-config
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
            - name: OTEL_EXPORTER_OTLP_INSECURE
              valueFrom:
                configMapKeyRef:
                  name: gobank-app-config
                  key: OTEL_EXPORTER_OTLP_INSECURE
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: gobank
spec:
  selector:
    app: auth
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: grpc
      port: 9090
      targetPort: grpc
