apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: gobank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: gobank/notification:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: gobank-app-config
                  key: KAFKA_BROKERS
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: gobank-app-config
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
            - name: OTEL_EXPORTER_OTLP_INSECURE
              valueFrom:
                configMapKeyRef:
                  name: gobank-app-config
                  key: OTEL_EXPORTER_OTLP_INSECURE
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 256Mi
