apiVersion: v1
kind: Secret
metadata:
  name: gobank-app-secret
  namespace: gobank
type: Opaque
stringData:
  JWT_SECRET: secret
  REDIS_PASSWORD: secret
  POSTGRES_USER: gobank
  POSTGRES_PASSWORD: secret
